import ToastProvider from "@/components/share/Toast/ToastProvider";
import QueryProvider from "@/lib/react-query/QueryProvider";
import StoreProvider from "@/lib/redux/provider/StoreProvider";
import type { Metadata } from "next";
import "./globals.css";

import Footer from "@/components/main/layout/Footer";
import Header from "@/components/main/layout/Header";
import { routing } from "@/i18n/routing";
import { hasLocale, NextIntlClientProvider } from "next-intl";
import { Inter } from "next/font/google";
import { notFound } from "next/navigation";
import { MainContentWrapper } from "@/lib/mainContentWrapper/MainContentWrapper";
import { AccessibilityControls } from "@/components/common/accessibility/AccessibilityControls";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Handicap International",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }
  return (
    <html lang={locale} className={inter.variable}>
      <body className="font-sans">
        <NextIntlClientProvider>
          <StoreProvider>
            <QueryProvider>
              <ToastProvider>
                <MainContentWrapper>
                  <AccessibilityControls />
                  <Header />
                  {children}
                  <Footer />
                </MainContentWrapper>
              </ToastProvider>
            </QueryProvider>
          </StoreProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
