import ToastProvider from "@/components/share/Toast/ToastProvider";
import QueryProvider from "@/lib/react-query/QueryProvider";
import StoreProvider from "@/lib/redux/provider/StoreProvider";
import type { Metadata } from "next";
import "./globals.css";

import Header from "@/components/main/layout/Header";
import { NextIntlClientProvider } from "next-intl";
import { Inter } from 'next/font/google';

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
});

export const metadata: Metadata = {
  title: "Handicap International",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.variable}>
      <body
        className="font-sans"
      >
        <StoreProvider>
          <QueryProvider>
            <ToastProvider>
              <NextIntlClientProvider>
                <Header/>
                {children}
                </NextIntlClientProvider>
            </ToastProvider>
          </QueryProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
